# Generated by Django 4.2.6 on 2023-11-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_agua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_colaborador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_agua.colaborador'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_sala',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_agua.sala'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_agua.usuario'),
        ),
    ]
