# Generated by Django 4.2.6 on 2023-11-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_agua', '0002_alter_pedido_id_colaborador_alter_pedido_id_sala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_agua.colaborador'),
        ),
    ]
